### ISSUE TITLE
Unknown panic on TCP write

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1088]
```
thread 'main' panicked at 'no Task is currently running', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:47:9

stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: std::panicking::begin_panic
  12: futures::task_impl::Task::will_notify_current
  13: <tokio_sync::task::atomic_task::CurrentTask as tokio_sync::task::atomic_task::Register>::register
  14: tokio_sync::task::atomic_task::AtomicTask::register
  15: tokio_reactor::registration::Registration::poll_ready
  16: tokio_reactor::registration::Registration::poll_write_ready
  17: tokio_reactor::poll_evented::PollEvented<E>::poll_write_ready
  18: <tokio_reactor::poll_evented::PollEvented<E> as std::io::Write>::write
  19: <tokio_tcp::stream::TcpStream as std::io::Write>::write
  20: <tokio_io::split::WriteHalf<T> as std::io::Write>::write
  21: <actix::io::FramedWrite<T,U> as core::ops::drop::Drop>::drop
  22: core::ptr::drop_in_place
  23: core::ptr::drop_in_place
  24: tokio_current_thread::scheduler::release_node
  25: std::thread::local::LocalKey<T>::with
  26: tokio_current_thread::scheduler::Scheduler<U>::tick
  27: tokio_current_thread::Entered<P>::block_on
  28: std::thread::local::LocalKey<T>::with
  29: tokio_reactor::with_default
  30: actix_rt::runtime::Runtime::block_on
  31: actix_rt::builder::SystemRunner::run
  32: witnet_node::actors::node::run
  33: witnet::cli::node::with_node::exec_cmd
  34: witnet::cli::exec
  35: witnet::main
  36: std::rt::lang_start::{{closure}}
  37: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  38: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  40: std::panicking::try
             at src/libstd/panicking.rs:281
  41: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  42: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  43: main
  44: __libc_start_main
```

**Comment by tmpolaczyk** [comment]
Possibly related

https://users.rust-lang.org/t/prevent-ending-tokio-task-before-ending-an-std-thread/26807/4

**Comment by igorline** [comment]
Getting this way more often on latest release 7.3 on my Pi node

**Comment by aesedepece** [comment]
> Getting this way more often on latest release 7.3 on my Pi node

With docker or directly on your OS? 

It's not that I have a clear idea on what impact would that have, it's just only for comparing with the Raspberry Pi B+ I have at home, which runs the node on Docker.

**Comment by igorline** [comment]
directly on raspbian, I think I also do have B+
