### ISSUE TITLE
Raspberry node panic on 7.3 testnet

### ISSUE THREAD

**Issue by igorline** [witnet/witnet-rust#1144]
Attaching the log:

```
thread 'main' panicked at 'no Task is currently running', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:47:9
stack backtrace:
   0:  0x14ebc48 - backtrace::backtrace::libunwind::trace::h9302baeb01f72358
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:  0x14ebc48 - backtrace::backtrace::trace_unsynchronized::h440dffb1a80d56c1
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:  0x14ebc48 - std::sys_common::backtrace::_print_fmt::ha20bba16c9bca8f3
                       at src/libstd/sys_common/backtrace.rs:77
   3:  0x14ebc48 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc829af81944f8ad2
                       at src/libstd/sys_common/backtrace.rs:59
   4:  0x150dfe0 - core::fmt::write::hb31d086ac39a7d95
                       at src/libcore/fmt/mod.rs:1052
   5:  0x14e51dc - std::io::Write::write_fmt::he2f347c296ab8924
                       at src/libstd/io/mod.rs:1426
   6:  0x14ee110 - std::sys_common::backtrace::_print::hf7615e4f01d2357a
                       at src/libstd/sys_common/backtrace.rs:62
   7:  0x14ee110 - std::sys_common::backtrace::print::h563690f4079eadc3
                       at src/libstd/sys_common/backtrace.rs:49
   8:  0x14ee110 - std::panicking::default_hook::{{closure}}::hc476a8c84cedfe4f
                       at src/libstd/panicking.rs:204
   9:  0x14edd6c - std::panicking::default_hook::h16cb7b563b9c9637
                       at src/libstd/panicking.rs:224
  10:  0x14ee7c0 - std::panicking::rust_panic_with_hook::hb046f51a13a6a258
                       at src/libstd/panicking.rs:472
  11:   0xdbfb28 - std::panicking::begin_panic::h4783167ff0f70e1a
  12:   0xdc15e4 - futures::task_impl::Task::will_notify_current::hf3721cad87a1e0a8
  13:   0xdb31d4 - <tokio_sync::task::atomic_task::CurrentTask as tokio_sync::task::atomic_task::Register>::register::h3024c0eb65282c3b
  14:   0xdb28c4 - tokio_sync::task::atomic_task::AtomicTask::register::hac758c9fae714fca
  15:   0xdad0ac - tokio_reactor::registration::Registration::poll_ready::hda21c190ad85841e
  16:   0xdacb50 - tokio_reactor::registration::Registration::poll_write_ready::h24276a0be110a049
  17:   0xd7fff4 - tokio_reactor::poll_evented::PollEvented<E>::poll_write_ready::ha5f7a7863ea3e3af
  18:   0xd8072c - <tokio_reactor::poll_evented::PollEvented<E> as std::io::Write>::write::h7935f87dd6922b44
  19:   0xd7ec0c - <tokio_tcp::stream::TcpStream as std::io::Write>::write::h6bcdd40998cd0b20
  20:   0x93cf14 - <tokio_io::split::WriteHalf<T> as std::io::Write>::write::h9d84e4b918f9a639
  21:   0xa701b8 - <actix::io::FramedWrite<T,U> as core::ops::drop::Drop>::drop::hbc2dc8d69b15deac
  22:   0x80e1a0 - core::ptr::drop_in_place::h611e52b2e490afd5
  23:   0x813f20 - core::ptr::drop_in_place::he27739e57124983e
  24:   0xd9e87c - tokio_current_thread::scheduler::release_node::hc7b5912aa2fef26d
  25:   0xd89b38 - core::ptr::drop_in_place::h211eb5275145468a
  26:   0xd8bcd0 - actix_rt::builder::SystemRunner::run::hab2063490ad22e48
  27:   0x81f730 - witnet_node::actors::node::run::h0bfd21484351b41e
  28:   0x50221c - witnet::cli::node::with_node::exec_cmd::hec7d1f8abd615d07
  29:   0x5450ac - witnet::cli::exec::hc3a95018a936d775
  30:   0x537310 - witnet::main::h4f48d690b0377550
  31:   0x52de60 - std::rt::lang_start::{{closure}}::hae45ca7fd9dcdfca
  32:  0x14ee284 - std::rt::lang_start_internal::{{closure}}::h282af46799d4ff01
                       at src/libstd/rt.rs:52
  33:  0x14ee284 - std::panicking::try::do_call::h38db37e59e79643a
                       at src/libstd/panicking.rs:305
  34:  0x14f61d8 - __rust_maybe_catch_panic
                       at src/libpanic_unwind/lib.rs:86
  35:  0x14eec18 - std::panicking::try::h97e92c0f9860eee1
                       at src/libstd/panicking.rs:281
  36:  0x14eec18 - std::panic::catch_unwind::he0917c0e501a9d7f
                       at src/libstd/panic.rs:394
  37:  0x14eec18 - std::rt::lang_start_internal::hc9d629535f156c19
                       at src/libstd/rt.rs:51
  38:   0x537458 - main
  39: 0x76bee678 - __libc_start_main
thread panicked while panicking. aborting.
```

**Comment by aesedepece** [comment]
Looks to me like a duplicate of #1088. Can you confirm?

**Comment by igorline** [comment]
Totally
