### ISSUE TITLE
Panicked at 'attempt to divide by zero'

### ISSUE THREAD

**Issue by clbartoli** [witnet/witnet-rust#1607]
When running a local testnet one of the nodes panicked with error `attempt to divide by zero`, in superblock.rs:533

![image](https://user-images.githubusercontent.com/52961116/94675290-ca6ae180-0319-11eb-97ac-48341cb568a7.png)

`[2020-09-30T10:24:12Z DEBUG witnet_node::actors::chain_manager] The current signing committee size is 2
[2020-09-30T10:24:12Z DEBUG witnet_data_structures::superblock] Created superblock #726 with hash_prev_block e6531de0d8445bcbec6849253f66a36cc6e4d541a50aba1c036dd225c9ed40fd, ARS 95e404ade5d45ea58d11a46fddc1bc3087bf50ecd712922e428ffc077def0f7d, signing_committee_length: 0, blocks ["#2901: 9ea8c70b81690872f42d700a7acb281676b19fc62a1c35d27271313140dc7bb9", "#2902: f545d6b1537972ce45f3c96f762a4140f8f3e19e2df96185d06954c5a8fe466c", "#2903: 58eb7482e58ff5c5c8d1d32b45eb6b80f7cad41760b7ac2067617c09bcc2ee2b"]
`

Logs of the node in the signing commitee that created a superblock with signing_committee_size = 0
[sign_comm_node.zip](https://github.com/witnet/witnet-rust/files/5305004/sign_comm_node.zip)

Logs of the node that panicked
[panicked_node.zip](https://github.com/witnet/witnet-rust/files/5305005/panicked_node.zip)

**Comment by lrubiorod** [comment]
The superblock received sometimes has a signing_committee lenght of 0, but I dont know why yet

**Comment by lrubiorod** [comment]
It is happen in the first superblock afer Superblock 0, the default current (empty) moves to previous and it is assigned a committee size of 0

**Comment by mariocao** [comment]
AFAIK, the `signing_committee_length` cannot be less than 1.

**Comment by tmpolaczyk** [comment]
This can still happen in a local testnet, but it will not happen in mainnet. So reopening but low priority.

**Comment by tmpolaczyk** [comment]
The error message has changed but the issue is still present, in a local testnet. This is in commit 59e90da85120d21586be803cf2b34077c1978d13.

```
[2021-12-31T12:31:58Z DEBUG witnet_node::actors::chain_manager::handlers] AddBlocks received while StateMachine is in state Synchronizing
[2021-12-31T12:31:58Z INFO  witnet_node::actors::chain_manager] Synchronization progress: 99.99% (1519859/1519873). Latest synced block is 5m 20s old.
[2021-12-31T12:31:58Z DEBUG witnet_node::actors::chain_manager::handlers] SyncWithCandidate(consolidation): sync done up to block #1519859 (last checkpoint of superblock #151986 reached)
[2021-12-31T12:31:58Z DEBUG witnet_node::actors::chain_manager::handlers] Will construct superblock during synchronization. Superblock index: 151986 Epoch 1519860
[2021-12-31T12:31:58Z DEBUG witnet_node::actors::chain_manager] GetBlocksEpochRange received (Included(1519850), Included(1519859))
[2021-12-31T12:31:58Z DEBUG witnet_node::actors::chain_manager] GetBlocksEpochRange received (Unbounded, Excluded(1519850))
[2021-12-31T12:31:58Z DEBUG witnet_node::actors::chain_manager] The node is not synced yet, so assume that superblock CheckpointBeacon { checkpoint: 0, hash_prev_block: 00000000000000000001000000000000000000007769746e65742d302e372e30 } is valid
thread 'main' panicked at 'division by zero', /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.9.0/src/lib.rs:38:1
stack backtrace:
   0:     0x55896e08180c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55896e08180c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55896e08180c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55896e08180c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55896e0a8c6c - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x55896e079725 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x55896e083430 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55896e083430 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55896e083430 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x55896e082fe5 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x55896e083c54 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:     0x55896dc323d2 - std::panicking::begin_panic::{{closure}}::he037d0b1ced17f4d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:544:9
  12:     0x55896dc326f9 - std::sys_common::backtrace::__rust_end_short_backtrace::hc190d9a0a87f17be
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55896dc32313 - std::panicking::begin_panic::hef716c5e29d9d52b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:543:12
  14:     0x55896db3afeb - primitive_types::U256::div_mod::h45fae21616b0f500
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.9.0/src/uint.rs:959:5
  15:     0x55896d6a5d1e - witnet_data_structures::chain::Hash::div_mod::h10cd4ec4d2063175
                               at /home/tomasz/projects/witnet-rust/data_structures/src/chain.rs:1109:22
  16:     0x55896d5a9703 - witnet_data_structures::superblock::calculate_superblock_signing_committee::h43221cd316f28725
                               at /home/tomasz/projects/witnet-rust/data_structures/src/superblock.rs:573:21
  17:     0x55896d5a87e4 - witnet_data_structures::superblock::SuperBlockState::build_superblock::h372d5b85e161a652
                               at /home/tomasz/projects/witnet-rust/data_structures/src/superblock.rs:425:37
  18:     0x55896c71fd0e - witnet_node::actors::chain_manager::ChainManager::construct_superblock::{{closure}}::ha2169f871a2adcfb
                               at /home/tomasz/projects/witnet-rust/node/src/actors/chain_manager/mod.rs:1557:38
  19:     0x55896c44b819 - <actix::fut::try_future::and_then::AndThen<A,B,F> as actix::fut::future::ActorFuture<Act>>::poll::hc1cf9e00f7d1c988
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/and_then.rs:65:28
  20:     0x55896c739d96 - <core::pin::Pin<P> as actix::fut::future::ActorFuture<A>>::poll::ha7c3e768b7903664
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/future/mod.rs:213:9
  21:     0x55896c735c15 - <F as actix::fut::try_future::ActorTryFuture<A>>::try_poll::h4f9367de34edc0d7
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/mod.rs:65:9
  22:     0x55896c44ab64 - <actix::fut::try_future::and_then::AndThen<A,B,F> as actix::fut::future::ActorFuture<Act>>::poll::hc0cdee4183b77f96
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/and_then.rs:63:33
  23:     0x55896c7398ae - <core::pin::Pin<P> as actix::fut::future::ActorFuture<A>>::poll::h4981615165917f5b
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/future/mod.rs:213:9
  24:     0x55896c751b2b - actix::fut::future::either::<impl actix::fut::future::ActorFuture<Act> for futures_util::future::either::Either<A,B>>::poll::h58d90457efd42b37
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/future/either.rs:36:35
  25:     0x55896c751f5e - <F as actix::fut::try_future::ActorTryFuture<A>>::try_poll::h9f7d98125bb56982
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/mod.rs:65:9
  26:     0x55896c44c1da - <actix::fut::try_future::and_then::AndThen<A,B,F> as actix::fut::future::ActorFuture<Act>>::poll::hc918ac31b3d1e327
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/and_then.rs:63:33
  27:     0x55896c4552fe - <F as actix::fut::try_future::ActorTryFuture<A>>::try_poll::h97f988387d04a0ca
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/mod.rs:65:9
  28:     0x55896c445a27 - <actix::fut::try_future::and_then::AndThen<A,B,F> as actix::fut::future::ActorFuture<Act>>::poll::h80b6b1b53835eb19
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/and_then.rs:63:33
  29:     0x55896c45548e - <F as actix::fut::try_future::ActorTryFuture<A>>::try_poll::hc593cff3badcc7ed
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/mod.rs:65:9
  30:     0x55896c43f18b - <actix::fut::try_future::and_then::AndThen<A,B,F> as actix::fut::future::ActorFuture<Act>>::poll::h34f78312eadf18ad
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/try_future/and_then.rs:63:33
  31:     0x55896c7e13d0 - <actix::fut::future::map::Map<Fut,F> as actix::fut::future::ActorFuture<A>>::poll::h7b3d1ddb0c574694
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/fut/future/map.rs:48:37
  32:     0x55896c7f4064 - actix::contextitems::ActorWaitItem<A>::poll::h0e60e80faa4ac9d6
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/contextitems.rs:35:15
  33:     0x55896c214386 - <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll::h9d0c7570a9b4857d
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.12.0/src/contextimpl.rs:375:24
  34:     0x55896c0a8c6e - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h5001c979be111eb8
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/core.rs:161:17
  35:     0x55896c1f3ec9 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h14afa3ef35a73027
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/loom/std/unsafe_cell.rs:14:9
  36:     0x55896c0a7528 - tokio::runtime::task::core::CoreStage<T>::poll::h697e9c4bdb2e8613
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/core.rs:151:13
  37:     0x55896c3a7b2e - tokio::runtime::task::harness::poll_future::{{closure}}::h7e27a96f4a8c662a
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:461:19
  38:     0x55896c105904 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he7426bffcbf11816
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  39:     0x55896c5efb42 - std::panicking::try::do_call::hdbed986fd3623889
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  40:     0x55896c5f889b - __rust_try
  41:     0x55896c5e1a0a - std::panicking::try::h27731773ef0c6615
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  42:     0x55896c5dd29b - std::panic::catch_unwind::h22bb8652a545a939
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  43:     0x55896c3a324c - tokio::runtime::task::harness::poll_future::h338e587d2520ea3c
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:449:18
  44:     0x55896c3ab6c4 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h63199c92af410925
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:98:27
  45:     0x55896c3bf3f4 - tokio::runtime::task::harness::Harness<T,S>::poll::h8bff15972940fbab
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:53:15
  46:     0x55896c46bbf2 - tokio::runtime::task::raw::poll::h5932e61e2154044d
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/raw.rs:113:5
  47:     0x55896ce684cf - tokio::runtime::task::raw::RawTask::poll::hde165aeacb301889
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/raw.rs:70:18
  48:     0x55896cdeed92 - tokio::runtime::task::LocalNotified<S>::run::h329e2477dc3ee89d
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/mod.rs:343:9
  49:     0x55896ce1242b - tokio::task::local::LocalSet::tick::{{closure}}::hd73409bf2b7823d5
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:521:54
  50:     0x55896ce65a05 - tokio::coop::with_budget::{{closure}}::h2a32ea06d72b5463
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:106:9
  51:     0x55896cde8c43 - std::thread::local::LocalKey<T>::try_with::h8b6440b21a597241
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  52:     0x55896cde795a - std::thread::local::LocalKey<T>::with::hc3871e48f11ef4f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  53:     0x55896ce123ba - tokio::coop::with_budget::ha1b8cda50077dc79
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:99:5
  54:     0x55896ce123ba - tokio::coop::budget::h576e8008ab868975
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:76:5
  55:     0x55896ce123ba - tokio::task::local::LocalSet::tick::h6a4283f1c640a24e
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:521:31
  56:     0x55896cdc1ec4 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h47260a8b5540c271
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:646:16
  57:     0x55896cdd0c3f - tokio::macros::scoped_tls::ScopedKey<T>::set::h37b9cf3b2f723838
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/macros/scoped_tls.rs:61:9
  58:     0x55896cdc194b - tokio::task::local::LocalSet::with::h0cf1ff53d6f6f1c4
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:559:9
  59:     0x55896cdc1c74 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::hfbbc04282f4c83c1
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:632:9
  60:     0x55896cdc1b42 - tokio::task::local::LocalSet::run_until::{{closure}}::ha413cd8da2290333
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:505:9
  61:     0x55896cdc784e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd5a0bdb5d0df6bf3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  62:     0x55896cdb3fdc - <core::pin::Pin<P> as core::future::future::Future>::poll::h4984bfdbdb2ec2e1
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
  63:     0x55896cdb8932 - tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}::hfb18b2c5da31128f
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:240:62
  64:     0x55896cdc0c54 - tokio::coop::with_budget::{{closure}}::hcc3caa422515160b
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:106:9
  65:     0x55896cdaff8c - std::thread::local::LocalKey<T>::try_with::h708b4d023461d4f0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  66:     0x55896cdaf5ee - std::thread::local::LocalKey<T>::with::h1a9c5946f06fa81e
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  67:     0x55896cdb7f5f - tokio::coop::with_budget::he611c0476a4aa3a6
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:99:5
  68:     0x55896cdb7f5f - tokio::coop::budget::h0901429367f98c49
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:76:5
  69:     0x55896cdb7f5f - tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::h80bbf32a154338a5
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:240:39
  70:     0x55896cdb94c2 - tokio::runtime::basic_scheduler::enter::{{closure}}::hc977e635a652de75
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:349:29
  71:     0x55896cdd0d5f - tokio::macros::scoped_tls::ScopedKey<T>::set::h5fa10b0fd1782a57
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/macros/scoped_tls.rs:61:9
  72:     0x55896cdb9429 - tokio::runtime::basic_scheduler::enter::hd7c4caa2edcc80ac
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:349:5
  73:     0x55896cdb7c0e - tokio::runtime::basic_scheduler::Inner<P>::block_on::h93db8b66c830a33c
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:230:9
  74:     0x55896cdb89ca - tokio::runtime::basic_scheduler::InnerGuard<P>::block_on::h4dcaf17a4db5ff48
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:501:9
  75:     0x55896cdb8cd5 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h159387ace00de7b6
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:186:24
  76:     0x55896cdd50a2 - tokio::runtime::Runtime::block_on::h2b37a483dce778d7
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/mod.rs:461:46
  77:     0x55896cdc19a0 - tokio::task::local::LocalSet::block_on::hffc2e2dcf4e02a23
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/task/local.rs:466:9
  78:     0x55896cdc2171 - actix_rt::runtime::Runtime::block_on::h7a1918cd2d964d8f
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.2.0/src/runtime.rs:85:9
  79:     0x55896cdd1f89 - actix_rt::system::SystemRunner::run::hfbca700cee16ea27
                               at /home/tomasz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.2.0/src/system.rs:167:15
  80:     0x55896c0946a8 - witnet_node::actors::node::run::hbc8342e49c9e171d
                               at /home/tomasz/projects/witnet-rust/node/src/actors/node.rs:67:5
  81:     0x55896b8824ac - witnet::cli::node::with_node::exec_cmd::h1c6e535bb2b2dfa3
                               at /home/tomasz/projects/witnet-rust/src/cli/node/with_node.rs:195:13
  82:     0x55896b77bf5c - witnet::cli::exec_cmd::h01f730540b2de2c6
                               at /home/tomasz/projects/witnet-rust/src/cli/mod.rs:68:31
  83:     0x55896b77bdd4 - witnet::cli::exec::h5bed00b342fb623e
                               at /home/tomasz/projects/witnet-rust/src/cli/mod.rs:59:5
  84:     0x55896b80ec2b - witnet::main::h143754d40cc80613
                               at /home/tomasz/projects/witnet-rust/src/main.rs:13:21
  85:     0x55896b79d88b - core::ops::function::FnOnce::call_once::h680f1e9d303b427e
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  86:     0x55896b83501e - std::sys_common::backtrace::__rust_begin_short_backtrace::hc713eed74be53086
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
  87:     0x55896b7ebf81 - std::rt::lang_start::{{closure}}::h991654abca2c84e7
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:146:18
  88:     0x55896e0814eb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc56adab7a77ec6e3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
  89:     0x55896e0814eb - std::panicking::try::do_call::h29f013120c5abc65
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  90:     0x55896e0814eb - std::panicking::try::h86d5b2b66caec4cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  91:     0x55896e0814eb - std::panic::catch_unwind::h7dd136d787f51397
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  92:     0x55896e0814eb - std::rt::lang_start_internal::{{closure}}::h4a199351e630a8a5
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
  93:     0x55896e0814eb - std::panicking::try::do_call::h20ceb9e5dff838c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  94:     0x55896e0814eb - std::panicking::try::hc2abb46a5e41bd43
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  95:     0x55896e0814eb - std::panic::catch_unwind::h52c3eb4408ad6dfb
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  96:     0x55896e0814eb - std::rt::lang_start_internal::hd15a47be08101c28
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
  97:     0x55896b7ebf50 - std::rt::lang_start::hbd95bef1149c7e33
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:145:17
  98:     0x55896b80eefc - main
  99:     0x7f1d9b6a9fd0 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
 100:     0x7f1d9b6aa07d - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:409:3
 101:     0x55896b761ca5 - _start
 102:                0x0 - <unknown>
[2021-12-31T12:31:58Z ERROR witnet_node::utils] Panic in ChainManager, shutting down system
Error: Non-zero exit code: 1
```

**Comment by aesedepece** [comment]
> This can still happen in a local testnet, but it will not happen in mainnet. So reopening but low priority.

Why so? :thinking:

**Comment by tmpolaczyk** [comment]
I think it has to do with the previous superblock index being 0. So it can happen in a testnet during the first blocks, and it could have happened in mainnet but also only during the first blocks.
