### ISSUE TITLE
Web3 lib refuses connection to unsynced providers

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-rust#2141]
When trying to connect to Etherereum node, `eth_syncing` is first RPC to be called. If `true` is returned, the centralized bridge will crash saying:

```
[2021-12-20T14:25:41Z ERROR witnet_centralized_ethereum_bridge] Failed to connect to ethereum node: Decoder error: Error("expected object or `false`, got `true`", line: 0, column: 0) thread 'main' panicked at 'ethereum node not running: "Decoder error: Error(\"expected object or `false`, got `true`\", line: 0, column: 0)"', bridges/centralized-ethereum/src/main.rs:110:18

stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: witnet_centralized_ethereum_bridge::run::{{closure}}
   4: tokio::macros::scoped_tls::ScopedKey<T>::set
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::macros::scoped_tls::ScopedKey<T>::set
   7: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
   8: tokio::runtime::Runtime::block_on
   9: witnet_centralized_ethereum_bridge::main

```

**Comment by tmpolaczyk** [comment]
The error is created here in the rust-web3 library:

https://github.com/tomusdrw/rust-web3/blob/1f807bb7c288a1d2668c691839381786065b2eac/src/types/sync_state.rs#L92

It looks like `true` is not a valid response for the `eth_syncing` method.

**Comment by tmpolaczyk** [comment]
As a workaround we could check for that particular error here:

https://github.com/witnet/witnet-rust/blob/97842745b0ceac43374de4b7fec80bcec1cc3180/bridges/centralized-ethereum/src/lib.rs#L92

```rust
if e.to_string() == "Decoder error: Error(\"expected object or `false`, got `true`\", line: 0, column: 0)" {
    return Ok(());
} else {
    log::error!("Failed to connect to ethereum node: {}", e);
    return Err(e);
}
```
